"""Generate the kiosk's "TOURNAMENT" wordmark texture for the module.

tools/gen_wordmark.ps1 renders the text with GDI+ (white, sheared, with a
baked-in dark drop shadow) to W*H {intensity, alpha} byte pairs; this script
tiles them into a GameCube IA8 texture (4x4-texel tiles, 32 bytes each, texel
= alpha byte then intensity byte) and writes src/melee/lb/lbwordmark_tex.inc,
which lbwordmark.c carries in the module and draws through the vanilla sprite
helper lb_800138EC. A preview PNG lands in build/wordmark.png.

Run from the repo root:  python tools/gen_wordmark.py [--font NAME] [--shear F]
"""
import argparse
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
W, H = 256, 48


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default="Franklin Gothic Medium")
    ap.add_argument("--shear", default="0.20")
    ap.add_argument("--text", default="TOURNAMENT")
    args = ap.parse_args()

    build = os.path.join(ROOT, "build")
    os.makedirs(build, exist_ok=True)
    raw = os.path.join(build, "wordmark.raw")
    png = os.path.join(build, "wordmark.png")
    cmd = ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File",
           os.path.join(HERE, "gen_wordmark.ps1"), "-Family", args.font, "-Text", args.text,
           "-W", str(W), "-H", str(H), "-Shear", args.shear, "-OutRaw", raw, "-OutPng", png]
    print(subprocess.run(cmd, check=True, capture_output=True, text=True).stdout.strip())

    px = open(raw, "rb").read()
    assert len(px) == W * H * 2, len(px)
    out = bytearray()
    for ty in range(H // 4):
        for tx in range(W // 4):
            for y in range(4):
                for x in range(4):
                    p = ((ty * 4 + y) * W + (tx * 4 + x)) * 2
                    out += bytes([px[p + 1], px[p]])  # alpha, intensity
    assert len(out) == W * H * 2

    inc = os.path.join(ROOT, "src", "melee", "lb", "lbwordmark_tex.inc")
    lines = [f"/* GENERATED by tools/gen_wordmark.py - do not edit. {W}x{H} GX IA8",
             f" * ({args.text!s}, {args.font}, shear {args.shear}), tiled 4x4, texel = alpha, intensity. */"]
    for o in range(0, len(out), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in out[o:o + 16]) + ",")
    with open(inc, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.relpath(inc, ROOT), f"({len(out)} bytes); preview", os.path.relpath(png, ROOT))


if __name__ == "__main__":
    main()
