"""Generate the SIS glyphs used for controller-button icons.

Melee's one text font is HSD_SisLib_FontAtlas: 287 glyphs of 32x32 4-bit
intensity (GameCube I4, 8x8 tiles), drawn by sislib as a flat colour with
the intensity as alpha. The kiosk overlays (lbbuttonglyph.c) draw a
GameCube button as a coloured shape glyph from this file with a font letter
laid over it, so the icons render inline with text at text scale.

Outputs:
  src/melee/lb/lbbuttonglyph_shapes.inc   flat u8[4][512] rows - the module
      serves these through SIS font slot 4 as glyph codes 0x4000+n (the
      vanilla atlas cannot grow); this is the path both builds use now.
  src/sysdolphin/baselib/sislib_font_extra.inc   TextGlyphTexture rows
      appended to the atlas in the (retired) shifted-DOL build.

Run from the repo root:  python tools/gen_button_glyphs.py
"""
import os

HERE = os.path.dirname(__file__)
OUT_ATLAS = os.path.join(HERE, "..", "src", "sysdolphin", "baselib", "sislib_font_extra.inc")
OUT_FLAT = os.path.join(HERE, "..", "src", "melee", "lb", "lbbuttonglyph_shapes.inc")
SS = 4  # supersampling per axis


def rounded_rect(x0, y0, x1, y1, r):
    """Coverage test for a rounded rectangle spanning [x0,x1]x[y0,y1]."""
    def inside(px, py):
        cx = min(max(px, x0 + r), x1 - r)
        cy = min(max(py, y0 + r), y1 - r)
        return (px - cx) ** 2 + (py - cy) ** 2 <= r * r
    return inside


def disc(cx, cy, r):
    return lambda px, py: (px - cx) ** 2 + (py - cy) ** 2 <= r * r


def union(*fs):
    return lambda px, py: any(f(px, py) for f in fs)


# name, shape, ink bbox (for the kerning table: left = x0, right = 31 - x1)
GLYPHS = [
    ("DISC",  disc(16.0, 16.0, 13.75),                       (2, 29)),
    ("RSQ",   rounded_rect(3.0, 3.0, 29.0, 29.0, 7.0),       (3, 28)),
    ("PILL",  rounded_rect(1.0, 9.0, 31.0, 23.0, 7.0),       (1, 30)),
    ("CROSS", union(rounded_rect(11.0, 2.0, 21.0, 30.0, 2.0),
                    rounded_rect(2.0, 11.0, 30.0, 21.0, 2.0)), (2, 29)),
]


def render(shape):
    px = [[0] * 32 for _ in range(32)]
    for y in range(32):
        for x in range(32):
            hits = 0
            for sy in range(SS):
                for sx in range(SS):
                    if shape(x + (sx + 0.5) / SS, y + (sy + 0.5) / SS):
                        hits += 1
            px[y][x] = round(15 * hits / (SS * SS))
    return px


def to_i4(px):
    out = bytearray()
    for ty in range(4):
        for tx in range(4):
            for y in range(8):
                for x in range(0, 8, 2):
                    a = px[ty * 8 + y][tx * 8 + x]
                    b = px[ty * 8 + y][tx * 8 + x + 1]
                    out.append((a << 4) | b)
    assert len(out) == 512
    return bytes(out)


def hex_rows(data):
    return ["    " + ", ".join(f"0x{b:02X}" for b in data[o:o + 16]) + ","
            for o in range(0, 512, 16)]


def main():
    rendered = [(name, to_i4(render(shape)), bbox) for name, shape, bbox in GLYPHS]

    atlas = ["/* GENERATED by tools/gen_button_glyphs.py - do not edit. Extra SIS glyphs",
             " * appended to HSD_SisLib_FontAtlas (indices 287+) in the shifted-DOL",
             " * build only; the module serves the same shapes via lbbuttonglyph_shapes.inc. */"]
    for i, (name, data, (x0, x1)) in enumerate(rendered):
        atlas += [f"/* {287 + i}: {name} ink x {x0}..{x1} */", "{ {"] + hex_rows(data) + ["} },"]
    with open(OUT_ATLAS, "w", newline="\n") as f:
        f.write("\n".join(atlas) + "\n")
    print("wrote", os.path.normpath(OUT_ATLAS))

    flat = ["/* GENERATED by tools/gen_button_glyphs.py - do not edit. The four button",
            " * shapes (32x32 I4, 0x200 bytes each) served by lbbuttonglyph.c's SIS font",
            " * slot as glyph codes 0x4000+n. Kerning pairs are in lbbuttonglyph.c. */"]
    for i, (name, data, (x0, x1)) in enumerate(rendered):
        flat += [f"/* {i}: {name} ink x {x0}..{x1}, kerning ({x0}, {31 - x1}) */", "{"] + hex_rows(data) + ["},"]
    with open(OUT_FLAT, "w", newline="\n") as f:
        f.write("\n".join(flat) + "\n")
    print("wrote", os.path.normpath(OUT_FLAT))

    print("kerning (left, right) per shape:")
    for i, (name, data, (x0, x1)) in enumerate(rendered):
        print(f"  {i} {name:5s} ({x0}, {31 - x1})")


if __name__ == "__main__":
    main()
